# Site wide configuration

title: Kodi Weatherholtz
locale: en_US
description: 
logo: profile-photo.jpg
search: true
comments: true
share: true
url: http://kweatherholtz.github.io
#url: http://localhost:4000

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
mathjax:     true
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Kodi Weatherholtz
  avatar: profile-photo.jpg
  email: kweatherholtz@bcs.rochester.edu
  disqus-shortname: kodiweatherholtz
  academia: rochester.academia.edu/KodiWeatherholtz
  twitter: #username
  facebook: #username
  github: kweatherholtz
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  bing-verify:
  google:
    plus: #username
    verify:
    ad-client:
    ad-slot:
    analytics: 
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-73268953-1', 'auto');
  ga('send', 'pageview');
    </script>
  
